# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c1d16072629115b6ba831c5c1b3dd087fc186bc2c586932598a8f16baba369c4215ee52f9a7066f250601f5b46211e2536812878522e6a485fa1f6b62791a0

test:
  secret_key_base: 024d56cb08244d3a505030bb41a1f086cfe469e887edc432628ab1c426fb301a3c67656705a3286b5c719ceb3895df23ef54b4c59e5a903351202473d379f67c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
